name: Deploy to Azure - Test

on: 
  workflow_dispatch:
    inputs:
      resourceGroup:
        description: 'Name of the target Azure resource group'
        required: true
        default: 'glitchio'
      sqlAdmin:
        description: 'Name for the sql server administrator'
        required: true
        default: 'sqladmin'
      slqAdminPass:
        description: 'Password for the sql admin server'     
        required: true
        default: '123asdQ!'

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@main
      name: Checkout
    - name: Read version
      id: version
      uses: juliangruber/read-file-action@v1
      with:
        path: ./.version
    - uses: azure/login@v1
      name: Azure Login
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x
    - name: Publish Client Web App
      run: dotnet publish ./src/ClientWebApp/ClientWeb.csproj --configuration release -o ./publish/client-web        
    - name: Deploy Client Web App
      uses: Azure/static-web-apps-deploy@v1
      with:
        action: "upload"
        skip_deploy_on_missing_secrets: true
        skip_app_build: true
        app_location: ./publish/client-web/wwwroot
        output_location: ./publish/client-web/wwwroot