name: Deploy to Azure

on: 
  workflow_dispatch:
    inputs:
      resourceGroup:
        description: 'Name of the target Azure resource group'
        required: true
        default: 'glitchio'
      sqlAdmin:
        description: 'Name for the sql server administrator'
        required: true
        default: 'sqladmin'
      slqAdminPass:
        description: 'Password for the sql admin server'     
        required: true
        default: '123asdQ!'

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@main
      name: Checkout
    - name: Read version
      id: version
      uses: juliangruber/read-file-action@v1
      with:
        path: ./.version
    - uses: azure/login@v1
      name: Azure Login
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
        
    - uses: azure/arm-deploy@v1
      name: Azure infrastructure
      with:
        deploymentName: ${{ format('main-v{0}.{1}', steps.version.outputs.content, github.run_number) }}
        resourceGroupName: ${{ github.event.inputs.resourceGroup }}
        template: ./deploy/main.bicep
        parameters: sqlAdmin=${{ github.event.inputs.sqlAdmin }} sqlAdminPass=${{ github.event.inputs.slqAdminPass }}
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x
    - name: Publish Profile Service
      run: dotnet publish ./src/ProfileService/Profile.Api/Profile.Api.csproj --configuration release -o ./publish/profile-service
    - name: Publish Client Web App
      run: dotnet publish ./src/ClientWebApp/ClientWeb.csproj --configuration release -o ./publish/client-webapp
    - name: Deploy Profile Service
      uses: azure/webapps-deploy@v2
      with: 
        app-name: glitchio-profile-service
        package: ./publish/profile-service
    - name: Deploy Client Web App
      uses: azure/webapps-deploy@v2
      with: 
        app-name: glitchio-client-webapp
        package: ./publish/client-webapp