name: Deploy to Azure

on: 
  workflow_dispatch:
    inputs:
      resourceGroup:
        description: 'Name of the target Azure resource group'
        required: true
        default: 'glitchio'
      sqlAdmin:
        description: 'Name for the sql server administrator'
        required: true
        default: 'sqladmin'
      slqAdminPass:
        description: 'Password for the sql admin server'     
        required: true
        default: '123asdQ!'

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@main
      name: Checkout
    
    - uses: azure/login@v1
      name: Azure Login
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
        
    - uses: azure/arm-deploy@v1
      name: Azure infrastructure
      with:
        resourceGroupName: ${{ github.event.inputs.resourceGroup }}
        template: ./deploy/main.bicep
        parameters: sqlAdmin=${{ github.event.inputs.sqlAdmin }} sqlAdminPass=${{ github.event.inputs.slqAdminPass }}
    - uses: Azure/static-web-apps-deploy@v1
      name: Deploy Client Web App
      with:
        azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_ASHY_FLOWER_0CF331703 }}
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        action: "upload"          
        app_location: "src/ClientWebApp"
        output_location: "wwwroot"